[tox]
envlist = py310,py311,py312
isolated_build = True

[testenv]
deps =
    pytest>=8.2.1
    pytest-cov>=5.0.0
    pandas>=2.2.2
    numpy>=1.26.4
    loguru>=0.7.2
    python-dotenv>=1.0.1
commands =
    pytest tests/ -v --cov=etl --cov-report=term-missing

[testenv:lint]
deps =
    ruff
commands =
    ruff check etl/ tests/

[testenv:format]
deps =
    ruff
commands =
    ruff format etl/ tests/
